import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Navbar from "./component/Navbar";
import Sidebar from "./component/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />

        {/* New nav */}
        <div className="grid grid-cols-[30vw_1fr]">
          <div className="flex h-screen w-62.5 overflow-hidden">
            <Sidebar />
          </div>

          <main className="overflow-y-auto bg-white">{children}</main>
        </div>
      </body>
    </html>
  );
}
