import type { Metadata } from "next";
import "../../globals.css"
import Sidebar from "./components/Sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <div className="flex h-screen w-full overflow-hidden">
      <Sidebar />
      <main className="min-h-0 flex-1 overflow-y-auto bg-white">{children}</main>
    </div>
  );
}
